ESA-EarthCODE/open-science-catalog-metadata

data/products/database-of-labelled-sentinel-1-interferograms-v20.json
{"filename": "database-of-labelled-sentinel-1-interferograms-v20.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/database-of-labelled-sentinel-1-interferograms-v20.json

data/variables/microphytoplankton-carbon.json
{"filename": "microphytoplankton-carbon.json", "item_type": "variables", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/variables/microphytoplankton-carbon.json

data/variables/phytoplankton-carbon.json
{"filename": "phytoplankton-carbon.json", "item_type": "variables", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/variables/phytoplankton-carbon.json

data/variables/export-production.json
{"filename": "export-production.json", "item_type": "variables", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/variables/export-production.json

data/variables/dissolved-organic-carbon.json
{"filename": "dissolved-organic-carbon.json", "item_type": "variables", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/variables/dissolved-organic-carbon.json

data/variables/particulate-inorganic-carbon.json
{"filename": "particulate-inorganic-carbon.json", "item_type": "variables", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/variables/particulate-inorganic-carbon.json

data/variables/particulate-organic-carbon.json
{"filename": "particulate-organic-carbon.json", "item_type": "variables", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/variables/particulate-organic-carbon.json

data/variables/phytoplankton-primary-production.json
{"filename": "phytoplankton-primary-production.json", "item_type": "variables", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/variables/phytoplankton-primary-production.json

data/products/monthly-global-microphytoplankton-carbon-dataset-9-km-oc-cci-v5.json
{"filename": "monthly-global-microphytoplankton-carbon-dataset-9-km-oc-cci-v5.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-microphytoplankton-carbon-dataset-9-km-oc-cci-v5.json

data/products/monthly-global-nanophytoplankton-carbon-dataset-9-km-oc-cci-v5.json
{"filename": "monthly-global-nanophytoplankton-carbon-dataset-9-km-oc-cci-v5.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-nanophytoplankton-carbon-dataset-9-km-oc-cci-v5.json

data/products/monthly-global-picophytoplankton-carbon-dataset-9-km-oc-cci-v5.json
{"filename": "monthly-global-picophytoplankton-carbon-dataset-9-km-oc-cci-v5.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-picophytoplankton-carbon-dataset-9-km-oc-cci-v5.json

data/products/monthly-global-export-production-based-on-henson-et-al-2011-dataset-9-km-oc-cci-v42.json
{"filename": "monthly-global-export-production-based-on-henson-et-al-2011-dataset-9-km-oc-cci-v42.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-export-production-based-on-henson-et-al-2011-dataset-9-km-oc-cci-v42.json

data/products/monthly-global-export-production-based-on-li-et-al-2016-dataset-9-km-oc-cci-v42.json
{"filename": "monthly-global-export-production-based-on-li-et-al-2016-dataset-9-km-oc-cci-v42.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-export-production-based-on-li-et-al-2016-dataset-9-km-oc-cci-v42.json

data/products/monthly-global-mixed-layer-depth-dataset-9-km-oc-cci-v5.json
{"filename": "monthly-global-mixed-layer-depth-dataset-9-km-oc-cci-v5.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-mixed-layer-depth-dataset-9-km-oc-cci-v5.json

data/products/monthly-global-microphytoplankton-carbon-dataset-9-km-oc-cci-v42.json
{"filename": "monthly-global-microphytoplankton-carbon-dataset-9-km-oc-cci-v42.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-microphytoplankton-carbon-dataset-9-km-oc-cci-v42.json

data/products/monthly-global-total-phytoplankton-carbon-dataset-9-km-oc-cci-v42.json
{"filename": "monthly-global-total-phytoplankton-carbon-dataset-9-km-oc-cci-v42.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-total-phytoplankton-carbon-dataset-9-km-oc-cci-v42.json

data/products/monthly-global-picophytoplankton-carbon-dataset-9-km-oc-cci-v42.json
{"filename": "monthly-global-picophytoplankton-carbon-dataset-9-km-oc-cci-v42.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-picophytoplankton-carbon-dataset-9-km-oc-cci-v42.json

data/products/monthly-global-chlorophyll-a-dataset-9-km-oc-cci-v42.json
{"filename": "monthly-global-chlorophyll-a-dataset-9-km-oc-cci-v42.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-chlorophyll-a-dataset-9-km-oc-cci-v42.json

data/products/monthly-global-mixed-layer-depth-dataset-9-km-oc-cci-v42.json
{"filename": "monthly-global-mixed-layer-depth-dataset-9-km-oc-cci-v42.json", "item_type": "products", "change_type": "Add", "user": "ewelina.dobrowolska@serco.com", "data_owner": false}
=> Add data/products/monthly-global-mixed-layer-depth-dataset-9-km-oc-cci-v42.json

data/products/database-of-labelled-sentinel-1-interferograms-v20.json, data/products/sm-based-approach-po-irrigation.json, data/products/sm-based-inversion-approach-ebro-irrigation.json, data/products/sm-based-inversion-approach-murray-darling-irrigation.json, data/variables/polar-lows.json
new products - irrigation project
=> add irrigation products, polar lows and volcnet

variables/catalog.json, variables/dry-tropospheric-correction/catalog.json, variables/ocean-surface-backscatter/catalog.json, variables/wet-tropospheric-correction/catalog.json
=> adding-varibles-hydrocoastal

projects/esa-science-hub-le-guillou/collection.json
Reverts ESA-EarthCODE/open-science-catalog-metadata#239
=> Revert "update-project"

variables/alpha-particles-differential-directional-flux/catalog.json
=> Add description to alpha-particles-differential-directional-flux variable

products/catalog.json, products/hydrology-4D/collection.json, projects/catalog.json, projects/deep-earth-system-data-lab/collection.json, variables/evaporation/catalog.json, variables/precipitation-amount/catalog.json, variables/snow-water-equivalent/catalog.json, variables/soil-moisture/catalog.json
add hydrology datacube and deepesdl project to open science catalog
=> add hydrology datacube and deepesdl project to osc

projects/4dmed-hydrology/collection.json, projects/deep-earth-system-data-lab/collection.json
-   refactored child href in deepesdl project
-   added child href in 4dmed-hydrology project
=> Refactor child link to hydrology4d product

eo-missions/smos/catalog.json, eo-missions/tandem-x/catalog.json, products/yield-data-field-level/collection.json, products/yield-data-nuts2-level/collection.json, projects/4dmed-hydrology/collection.json, projects/deep-earth-system-data-lab/collection.json, projects/mass-balance-and-ice-dynamics-of-antarctic-peninsula-glaciers-mit-ap/collection.json, themes/cryosphere/catalog.json, themes/land/catalog.json, themes/oceans/catalog.json, variables/digital-elevation-terrain-model-dem/catalog.json, variables/fronts/catalog.json, variables/glacier-mass-balance-ice-sheet-mass-balance/catalog.json, variables/ocean-currents/catalog.json, variables/oil-spills/catalog.json, variables/sargassum/catalog.json, variables/sea-surface-salinity/catalog.json, variables/surface-currents/catalog.json, variables/wind-stress/catalog.json
We should check why PR #344 did not fail on this. Is an old version running?
=> Fix links in new products

experiments/catalog.json, experiments/esa-cci-permafrost/record.json, products/catalog.json, products/esa-cci-permafrost/collection.json, projects/deep-earth-system-data-lab/collection.json, variables/catalog.json, variables/permafrost-area-fraction/catalog.json, variables/solid-earth-subsurface-temperature/catalog.json, variables/surface-temperature/catalog.json, workflows/catalog.json, workflows/esa-cci-permafrost/record.json
This PR adds a new dataset collection: esa-cci-permafrost and its corresponding workflow/experiment to the repository.
=> Add new dataset collection: esa-cci-permafrost and workflow/experiment: esa-cci-permafrost

eo-missions/sentinel-3/catalog.json, products/catalog.json, products/sentinel3-ampli-ice-sheet-elevation/collection.json, projects/catalog.json, projects/sral-processing-landice/collection.json, themes/cryosphere/catalog.json, variables/ice-sheet-topography/catalog.json
adding products to the project, rename project name
=> placing-s3-products

products/catalog.json, products/grounded-eo-database/collection.json, projects/catalog.json, projects/grounded-eo/collection.json
Description of Grounded-EO dataset published on zenodo
=> publish-grounded-eo-database
